// Per-tenant Web App Manifest. Served at /manifest.webmanifest.
//
// The browser fetches this when it sees `<link rel="manifest">` in
// the HTML head. Because each tenant has its own host (subdomain or
// custom domain), middleware injects `x-tenant-id` and
// `x-tenant-config-json` headers; we read those here and return a
// manifest customized to the league: name, short_name, theme color,
// icons, start_url. Result: when a captain installs the SFBL site,
// they get an SFBL-branded home-screen icon; KCSL captains get a
// KCSL-branded one — same code, different output per host.
//
// FUTURE: tenant config grows a `pwa_icon_url` (or we standardize
// `theme.logo_url` to be 512x512). For now we point at the tenant's
// logo_url and fall back to a generic asset if missing — bad-aspect
// or low-res icons will still install but look mediocre until the
// commissioner uploads proper PWA icons.

import { headers } from "next/headers";
import { NextResponse } from "next/server";

export const dynamic = "force-dynamic";

interface TenantTheme {
  primary?: string;
  accent?: string;
  logo_url?: string;
}
interface TenantConfig {
  name?: string;
  abbrev?: string;
  short?: string;
  theme?: TenantTheme;
}

export function GET() {
  const h = headers();
  const tenantId = h.get("x-tenant-id");
  const configJson = h.get("x-tenant-config-json");
  let cfg: TenantConfig = {};
  if (configJson) {
    try {
      cfg = JSON.parse(configJson) as TenantConfig;
    } catch {
      /* fall through */
    }
  }

  const name = cfg.name ?? "League";
  const shortName = cfg.abbrev ?? cfg.short ?? tenantId ?? "League";
  const themeColor = cfg.theme?.primary ?? "#0a0e1c";

  const manifest = {
    name,
    short_name: shortName,
    description: `${name} — captain portal, schedule, scores, standings.`,
    start_url: "/?pwa=1",
    scope: "/",
    display: "standalone",
    display_override: ["window-controls-overlay", "standalone"],
    orientation: "portrait",
    background_color: themeColor,
    theme_color: themeColor,
    icons: [
      // Three icon variants for full PWA coverage:
      //   - 192 (any)        — home screen tile on most platforms
      //   - 512 (any)        — splash screen, large tiles, task switcher
      //   - 512 (maskable)   — Android adaptive icons; logo sits in
      //                        the inner 80% safe area so the OS can
      //                        crop to circle/squircle without losing
      //                        any of the brand mark
      // Generated by `node scripts/build-pwa-icons.js` from the
      // tenant's vertical logo on a brand-color square.
      {
        src: "/icons/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
    // Long-press home-screen icon shortcuts. Power users tap once
    // to deep-link straight to scores or standings without going
    // through the homepage.
    shortcuts: [
      {
        name: "Scores",
        short_name: "Scores",
        url: "/scores",
        description: "Recent finals and box scores",
      },
      {
        name: "Standings",
        short_name: "Standings",
        url: "/standings",
        description: "Division standings",
      },
      {
        name: "Schedule",
        short_name: "Schedule",
        url: "/schedule",
        description: "Upcoming games",
      },
    ],
    categories: ["sports", "lifestyle"],
  };

  return NextResponse.json(manifest, {
    headers: {
      "content-type": "application/manifest+json",
      // Brief cache so a config change picks up within ~5 min on
      // installed PWAs without forcing reinstall.
      "cache-control": "public, max-age=300",
    },
  });
}
