#!/usr/bin/env bash
# Pull GameSlate's scheduling engine (and its engine tests) into this repo.
#
# The Build Schedule tab can run on either of two engines (see
# components/admin/ScheduleGenerator.tsx and lib/gameslate/README.md):
#
#   lib/schedule-generator.ts   the platform engine, what every league has
#                               always built its season with. Untouched.
#   lib/gameslate/              a VERBATIM copy of the GameSlate repo's
#                               lib/schedule-generator.ts and
#                               lib/schedule-conflicts.ts, for the leagues
#                               that opt in with flags.gameslate_scheduler.
#
# GameSlate's engine was itself lifted from this repo on 2026-08-13 and the
# two then drifted for three weeks, each fixing bugs the other still had.
# This script is how that stops happening: never edit lib/gameslate/ by hand.
# Fix it in GameSlate, run this, commit both repos.
#
#   scripts/sync-gameslate-engine.sh                       # ~/Desktop/gameslate
#   GAMESLATE=/path/to/gameslate scripts/sync-gameslate-engine.sh
#
# Then: npm run typecheck && npx vitest run tests/gameslate
set -euo pipefail

SRC="${GAMESLATE:-$HOME/Desktop/gameslate}"
HERE="$(cd "$(dirname "$0")/.." && pwd)"

if [ ! -f "$SRC/lib/schedule-generator.ts" ]; then
  echo "No GameSlate checkout at $SRC (set GAMESLATE=...)" >&2
  exit 1
fi

REV="$(git -C "$SRC" rev-parse --short HEAD 2>/dev/null || echo unknown)"
DATE="$(git -C "$SRC" log -1 --format=%cs 2>/dev/null || date +%F)"

mkdir -p "$HERE/lib/gameslate" "$HERE/tests/gameslate"

for f in schedule-generator.ts schedule-conflicts.ts; do
  {
    echo "// COPIED FROM GAMESLATE — do not edit this file here."
    echo "// Source: gameslate/lib/$f at $REV ($DATE)."
    echo "// Refresh with scripts/sync-gameslate-engine.sh. See lib/gameslate/README.md."
    echo
    cat "$SRC/lib/$f"
  } > "$HERE/lib/gameslate/$f"
done

# The engine's own tests come along, so the copy is proven here and not only
# over there. Only the pure ones: bracket tests belong to GameSlate's bracket
# builder (this repo has its own), and the file-reading ones test its UI.
n=0
for t in "$SRC"/tests/*.test.ts; do
  b="$(basename "$t")"
  if grep -q "lib/bracket-engine\|node:fs" "$t"; then continue; fi
  if ! grep -q "lib/schedule-generator\|lib/schedule-conflicts" "$t"; then continue; fi
  sed -E "s#(['\"])\.\./lib/schedule-(generator|conflicts)(['\"])#\1@/lib/gameslate/schedule-\2\3#g" \
    "$t" > "$HERE/tests/gameslate/$b"
  n=$((n + 1))
done

echo "lib/gameslate/{schedule-generator,schedule-conflicts}.ts and $n tests synced from GameSlate $REV ($DATE)"
