// COPIED FROM GAMESLATE — do not edit this file here.
// Source: gameslate/lib/schedule-generator.ts at 2810c62 (2026-09-04).
// Refresh with scripts/sync-gameslate-engine.sh. See lib/gameslate/README.md.

// Round-robin schedule generator.
//
// Inputs are the ones a league director actually thinks in: which teams, which
// days of the week, from when to when, which dates are off, which fields and
// what times each field runs, how many games a team plays in a week, and which
// matchups must never happen.
//
// Deliberately pure — no Firestore, no React, no clock. Everything derives from
// the arguments, so the same inputs always produce the same schedule. That is
// what makes the admin preview trustworthy: what is on screen is exactly what
// gets written.
//
// Structure:
//   1. Build the real calendar first (days of week, blackouts, end date), so a
//      "week" is a set of actual dates rather than an index. Off days and off
//      weeks fall out of this naturally instead of being special cases.
//   2. Pair the teams with the circle method, so everyone meets everyone.
//   3. Drop matchups that are blocked, by organisation or by hand.
//   4. Drop the pairings into the calendar's slots.
//
// Anything that cannot be placed is reported, never silently dropped.

import {
  legalFieldsFor,
  minutesOf,
  type ConflictGame,
  type ConflictTeam,
} from "./schedule-conflicts";

export interface GeneratorTeam {
  id: string;
  name: string;
  /** Free-text organisation/club. Teams sharing one never play each other.
   *  Blank or missing means "no club", and those teams can play anyone. */
  organization?: string | null;
  /** Dates this team cannot play, YYYY-MM-DD. Distinct from the league-wide
   *  off days: "Riverhead is away the weekend of the 20th" only blocks that
   *  team, and the rest of the division plays as normal. */
  unavailable?: string[];
  /** This team's home field. Games are nudged towards it, and the team is
   *  made the home side when a game lands there. Ties into a home-field
   *  discount, where a club is expected to host a share of its games. */
  homeField?: string | null;
  /** Earliest start this team can make, HH:MM. A carpool that gets out of
   *  work at six cannot play the 5:30 slot. Hard wall. */
  earliestTime?: string | null;
  /** Latest start this team will accept, HH:MM. Hard wall. */
  latestTime?: string | null;
  /**
   * Fields this team may play at AT ALL. Distinct from `homeField`, which is a
   * preference worth a scoring nudge: this is a hard wall. A 14U squad that
   * needs a full-size diamond, or a club with permits for only its own park,
   * cannot simply be "nudged" elsewhere.
   *
   * Empty or missing means unrestricted, which is the right default — most
   * teams travel, and requiring every team to be configured before a schedule
   * can be built would make the feature unusable at 185 teams.
   */
  allowedFields?: string[] | null;
  /** Weekdays (0 = Sunday .. 6 = Saturday) this team can play. Empty or null
   *  means any of the division's nights. A coach who can only do Tuesdays. */
  allowedDays?: number[] | null;
  /** Cap on this team's games in any one week, overriding the division. */
  maxGamesPerWeek?: number | null;
  /** Travel zone (an area name). Games at a field in another zone count as
   *  travel and are steered away from, or capped per week. */
  zone?: string | null;
  /** Weekdays (0..6) on which this team must play at its home field. */
  homeOnlyDays?: number[] | null;
  /** This team's own travel radius in miles from its home field. */
  maxMilesFromHome?: number | null;
  /** This team's own season game count, overriding targetGamesPerTeam. */
  targetGames?: number | null;
  /** Drive minutes from home field cap for this team, overriding the league. */
  maxMinutesFromHome?: number | null;
}

/** A field and the start times available ON THAT FIELD. Times are per field,
 *  not global: one park might run 5:30 and 7:00 while another only has 5:30,
 *  and a shared time list would invent slots that do not exist. */
export interface GeneratorField {
  name: string;
  /** Different start times on given weekdays (0 = Sunday .. 6 = Saturday),
   *  the Saturday day-game list for a park that runs 5:30/7:00 on weeknights.
   *  A day with no entry falls back to `times`. */
  timesByDay?: Record<number, string[]> | null;
  /** Lights out: no game may START after this time, optionally only between
   *  two dates (April dusk vs June). A park with no lights in the spring. */
  latestStart?: string | null;
  latestStartFrom?: string | null;
  latestStartUntil?: string | null;
  /** Travel zone this field sits in, matched against team zones. */
  zone?: string | null;
  /** Location, for mile based travel rules. */
  lat?: number | null;
  lng?: number | null;
  /** No lights: the last start each date is sunset minus the game length,
   *  computed from lat/lng. Ignored until the field is located. */
  noLights?: boolean | null;
  /** Start times on this field, 24h HH:MM, e.g. ["17:30", "19:00"]. */
  times: string[];
  /** Not usable before this date, YYYY-MM-DD. The school field that only
   *  frees up once school lets out, say. */
  availableFrom?: string | null;
  /** Not usable after this date, YYYY-MM-DD. The park permit that expires. */
  availableUntil?: string | null;
  /** Weekdays this field can be used, 0 = Sunday .. 6 = Saturday. Empty or
   *  missing means any day the season plays. The field the league only has on
   *  Saturdays. */
  days?: number[] | null;
  /** Specific dates this one field is closed, YYYY-MM-DD. Distinct from the
   *  league-wide blackout dates: one field down for maintenance while the
   *  rest of the complex plays on. */
  closedDates?: string[] | null;
}

export interface GeneratorOptions {
  teams: GeneratorTeam[];
  /** Season start, YYYY-MM-DD. The first game lands on or after this. */
  startDate: string;
  /** Last possible date, YYYY-MM-DD. When set it beats `weeks`. */
  endDate?: string;
  /** How many weeks of games, when no endDate is given. */
  weeks?: number;
  /**
   * Which weekdays games are played on. 0 = Sunday .. 6 = Saturday.
   * A weeknight division might be [2] (Tuesdays); a weekend division playing
   * Saturday and Sunday is [6, 0]. Defaults to the weekday of startDate.
   */
  daysOfWeek?: number[];
  /**
   * Dates with no games: holiday weekends, field closures, tournament weekends.
   * A blacked-out date is removed from the calendar, so the season stretches by
   * a week rather than losing those games.
   */
  blackoutDates?: string[];
  /** Fields, each with its own available start times. */
  fields: GeneratorField[];
  /**
   * Matchups blocked by hand, as pairs of team ids. These two never play each
   * other. Order within a pair does not matter.
   */
  blockedPairs?: [string, string][];
  /** Written onto each game so standings group correctly. */
  division?: string;
  /**
   * How many games each team plays per week. Default 1. Nothing assumes 1: a
   * weeknight division might run two, a weekend division three.
   */
  gamesPerWeek?: number;
  /**
   * When gamesPerWeek is 2+, are those against the SAME opponent (a
   * doubleheader: back to back on one field, home/away alternating) or
   * DIFFERENT opponents (that many rounds packed into the week)?
   */
  weeklyPairing?: "same-opponent" | "different-opponents";
  /**
   * Games that already exist — other divisions generated earlier, hand-added
   * rows, last week's fixtures. Their date+field+time slots are treated as
   * taken, and their teams as busy at those times.
   *
   * Without this, generating division by division silently double-books: the
   * 12U run has no idea the 10U run already took Cedar Hill at 5:30. That is
   * the single most common way a multi-division league's schedule breaks.
   */
  existingGames?: ConflictGame[];
  /**
   * How long a game occupies its field, in minutes. 0 (default) means a slot
   * is only "taken" by an exact same-start game. Set it and near-misses like
   * 17:30 against 18:00 on one field stop being scheduled.
   */
  gameMinutes?: number;
  /**
   * Stop once every allowed pair has met this many times. 1 is a single round
   * robin, 2 a double. Unset (default) keeps cycling matchups until the
   * calendar runs out, which is the "fill the season" behaviour.
   */
  maxCycles?: number;
  /**
   * Groups of team ids that can never play at overlapping times, because they
   * share a coach, a family, or a bench. Works across divisions too: ids in
   * `existingGames` are matched through the same groups.
   */
  linkedTeamIds?: string[][];
  /** Hard cap on one team's games in a single day. */
  maxPerTeamPerDay?: number;
  /** Minimum minutes between the END of one of a team's games and the start
   *  of its next game on the same day. Needs `gameMinutes` to mean much. */
  minGapMinutes?: number;
  /** Maximum wait between a team's games on one day: a second game must
   *  start within this many minutes of the previous one ending. Keeps a
   *  Saturday from being 9am and 5pm with a dead afternoon. */
  maxGapMinutes?: number;
  /** Minimum days between a team's games on DIFFERENT days. 2 means a team
   *  that played Tuesday cannot play again until Thursday. Same-day games
   *  are governed by the gap rules, not this. */
  minDaysRest?: number;
  /** Fill early slots first, late slots first, or spread teams across slot
   *  times evenly (default). */
  slotPreference?: "early" | "late" | "balanced";
  /** Prefer fields in the order given: the first field is the showcase field
   *  that should fill first. Off by default. */
  prioritizeFieldOrder?: boolean;
  /**
   * Vary the layout without changing the inputs. The generator is otherwise
   * deterministic: same inputs, same schedule. A seed shuffles the pairing
   * order and breaks slot ties differently, so different seeds produce
   * different but equally valid schedules. That is what lets an admin
   * generate a handful of options and keep the best. Same seed always
   * reproduces the same schedule, so the preview stays trustworthy.
   */
  seed?: number;
  /**
   * Matchups pinned to a date or a week: opening day rivalries, a rivalry
   * week, a scheduled grudge match. Each is placed first at its target, and
   * the rest of the schedule is built around it. In a single round robin a
   * pinned pair meets once, at the pin. One placed here is removed from the
   * auto round robin so it is never double scheduled; a pin that cannot fit
   * its target is scheduled normally instead, with a warning.
   */
  requiredMatchups?: RequiredMatchup[];
  /** Stop once each team has this many games: a 14 game season for 10 teams,
   *  balanced across opponents, instead of a whole number of round robins. */
  targetGamesPerTeam?: number;
  /** avoid: keep a team to one game a day when the calendar allows it.
   *  prefer: pull a team's second game of the day next to its first (the
   *  Saturday doubleheader league). allow: no opinion, the day cap rules. */
  doubleheaders?: "avoid" | "allow" | "prefer";
  /** Keep every team's weekend and weeknight game counts close. */
  weekendBalance?: boolean;
  /** Never schedule a rematch within this many weeks of the last meeting. */
  noRematchWeeks?: number;
  /** A team is never home (or away) more than this many games in a row. */
  maxConsecutiveHome?: number;
  maxConsecutiveAway?: number;
  /** Sub-pools inside a division: teamId -> pool label. In-pool pairs meet
   *  poolCycles times, cross-pool pairs crossPoolCycles times (0 = never). */
  pools?: Record<string, string> | null;
  poolCycles?: number;
  crossPoolCycles?: number;
  /** Umpire capacity: at most this many games may start at overlapping times
   *  league-wide, whatever the number of fields. */
  maxSimultaneousGames?: number;
  /** Turnaround on a field between games (lining, raking): two games on the
   *  same field must be gameMinutes + this far apart. */
  fieldBufferMinutes?: number;
  /** Soft cost for a team playing outside its zone (default 6 when zones are
   *  in use), and a hard weekly cap on out-of-zone games per team. */
  travelPenalty?: number;
  maxOutOfZonePerWeek?: number;
  /** With an odd team count: "bye" sits one team out each round (default);
   *  "doubleheader" gives the bye team a game against the team that has had
   *  the fewest extra games, so everyone plays every week. */
  oddTeams?: "bye" | "doubleheader";
  /** balanced: even out season home counts (default). alternate: a team
   *  that was home last time is away next time whenever the field allows. */
  homeAwayPattern?: "balanced" | "alternate";
  /** Two same-day games at DIFFERENT fields need at least this many minutes
   *  between them (drive time), on top of the normal gap rule. */
  travelMinutesBetweenFields?: number;
  /** Weekend method: every team gets one weekday game and one weekend game
   *  each week (for two-game weeks), never two of the same kind. */
  weekendMethod?: boolean;
  /** Treat Friday as a weekend day for balance and the weekend method. */
  fridayIsWeekend?: boolean;
  /** Spread each team's games across the weekdays it plays on. */
  balanceDays?: boolean;
  /** Mile based travel, measured between field locations. A team with a home
   *  field never plays farther than this from it (league default, per team
   *  override), never travels farther than this between same day games, and
   *  with preferCloser the nearer field wins ties. */
  maxMilesFromHome?: number;
  maxMilesFromLast?: number;
  preferCloser?: boolean;
  /** "require": a game must be played at the host's home field whenever the
   *  host has one. Default "prefer", a soft nudge. */
  homeFieldRule?: "prefer" | "require";
  /** Dates that are game days no matter the weekday, e.g. a Saturday
   *  Opening Day for a weeknight league. Win over blackouts. */
  extraDates?: string[];
  /** No team sits longer than this many days between games. Teams that have
   *  waited longest go first each week; overruns are reported. */
  maxIdleDays?: number;
  /** Drive minutes between fields, by field name, from a routing service.
   *  When present it replaces the flat travelMinutesBetweenFields for that
   *  pair and powers maxMinutesFromHome. */
  driveMinutes?: Record<string, Record<string, number>> | null;
  /** A team with a home field never plays farther than this many drive
   *  minutes from it. */
  maxMinutesFromHome?: number;
  /** "strict" weighs start time balance much harder, so no team collects the
   *  9am or the late slot. Default "normal". */
  slotBalance?: "normal" | "strict";
  /** Home and home: when two teams meet again, the previous visitor hosts
   *  (unless a home field rule says otherwise). */
  pairAlternate?: boolean;
  /** Games already played before a mid season rebuild. Each entry removes one
   *  meeting of that pair from the round robin and seeds the counts (games,
   *  home/away, last meeting, dates) so every rule continues where it was. */
  alreadyPlayed?: { a: string; b: string; home?: string; date?: string; week?: number }[];
  /** Added to every week number, so a rebuild from week 7 keeps counting. */
  weekOffset?: number;
  /** Week template: the only start times this division uses on each weekday
   *  (0 = Sunday). Days not listed keep every field time. */
  allowedStartsByDay?: Record<number, string[]> | null;
  /** Minutes east of UTC for local sunset math. Default: the runtime's zone. */
  tzOffsetMinutes?: number | ((date: string) => number);
}

/** Great-circle distance in miles between two points. */
export function milesBetween(lat1: number, lng1: number, lat2: number, lng2: number): number {
  const R = 3958.8;
  const toRad = (d: number) => (d * Math.PI) / 180;
  const dLat = toRad(lat2 - lat1);
  const dLng = toRad(lng2 - lng1);
  const a =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(toRad(lat1)) * Math.cos(toRad(lat2)) * Math.sin(dLng / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(a));
}

export interface RequiredMatchup {
  /** Team ids. Order only sets the default home/away when neither has the
   *  chosen field as a home field. */
  a: string;
  b: string;
  /** Pin to a specific date, YYYY-MM-DD. Takes priority over `week`. */
  date?: string;
  /** Pin to a 1-based week of the season instead of a single date. */
  week?: number;
  /** Shown on the game, e.g. "Opening Day" or "Rivalry Week". */
  label?: string;
  /** Pin to this start time (HH:MM) and/or this field as well. */
  time?: string;
  field?: string;
}

export interface GeneratedGame {
  date: string;
  time: string;
  field: string;
  away_team_id: string;
  home_team_id: string;
  division?: string;
  week: number;
  status: "scheduled";
  /** Set when this game was pinned via requiredMatchups. */
  required?: boolean;
  /** The pin's label, e.g. "Opening Day". */
  label?: string;
}

export interface GeneratorResult {
  games: GeneratedGame[];
  /** Dates the schedule actually uses, in order. */
  dates: string[];
  /** Pairs skipped because both teams belong to one organisation. */
  skippedSameOrg: { a: string; b: string; organization: string }[];
  /** Pairs skipped because the admin blocked that specific matchup. */
  skippedBlocked: { a: string; b: string }[];
  /** Pairs with no slot left (more matchups than the calendar can hold). */
  unscheduled: { a: string; b: string }[];
  /** Pairs whose teams' allowed-field sets do not overlap, so no field in the
   *  league can legally host them. A configuration problem, not a capacity
   *  one — worth telling the admin apart from `unscheduled`. */
  noLegalField: { a: string; b: string }[];
  /** Slots skipped because an existing game already occupies them. Counted so
   *  the admin can see the generator worked around the rest of the league
   *  rather than wondering why it produced fewer games than expected. */
  slotsBlockedByExisting: number;
  /** True once every allowed pair has been scheduled at least once. */
  everyPairPlayed: boolean;
  warnings: string[];
}

export interface ScheduleQuality {
  /** 0-100, higher is better. A blend of the metrics below. */
  score: number;
  /** Largest home-minus-away gap on any team. 0 is perfect balance. */
  homeAwaySpread: number;
  /** 0-1, how evenly each team is spread across the start times. 1 = every
   *  team gets an even mix, 0 = someone plays every game in one slot. */
  slotFairness: number;
  /** Games that could not be placed. */
  unscheduled: number;
  /** 0-1, how evenly each team is spread across the fields (venue balance). */
  fieldFairness: number;
  /** 0-1, how close each team's weekend and weeknight counts are. */
  weekendBalance: number;
  /** Letter grade for the humans. */
  grade: string;
}

/** Score a generated schedule so an admin can compare layouts and keep the
 *  best. Pure: same games in, same score out. */
export function scheduleQuality(
  games: GeneratedGame[],
  unscheduled = 0,
): ScheduleQuality {
  const home: Record<string, number> = {};
  const away: Record<string, number> = {};
  const bySlot: Record<string, Record<string, number>> = {};
  const byField: Record<string, Record<string, number>> = {};
  const wk: Record<string, number> = {};
  const wd: Record<string, number> = {};
  const total: Record<string, number> = {};
  for (const g of games) {
    home[g.home_team_id] = (home[g.home_team_id] ?? 0) + 1;
    away[g.away_team_id] = (away[g.away_team_id] ?? 0) + 1;
    const weekend = g.date ? (() => { const w = weekdayOf(g.date); return w === 0 || w === 6; })() : false;
    for (const id of [g.home_team_id, g.away_team_id]) {
      total[id] = (total[id] ?? 0) + 1;
      (bySlot[id] ??= {})[g.time] = ((bySlot[id] ??= {})[g.time] ?? 0) + 1;
      const fk = String(g.field ?? "").trim().toLowerCase();
      (byField[id] ??= {})[fk] = ((byField[id] ??= {})[fk] ?? 0) + 1;
      if (weekend) wk[id] = (wk[id] ?? 0) + 1; else wd[id] = (wd[id] ?? 0) + 1;
    }
  }
  const teams = Object.keys(total);
  let spread = 0;
  for (const id of teams) {
    spread = Math.max(spread, Math.abs((home[id] ?? 0) - (away[id] ?? 0)));
  }
  // Slot fairness: for each team, 1 minus how dominant its most-used slot is,
  // scaled so a perfectly even split scores 1. Averaged across teams.
  let fairSum = 0;
  let distinctSlots = new Set(games.map((g) => g.time)).size || 1;
  for (const id of teams) {
    const counts = Object.values(bySlot[id] ?? {});
    const n = total[id] ?? 0;
    if (n === 0 || distinctSlots === 1) {
      fairSum += 1;
      continue;
    }
    const maxShare = Math.max(...counts) / n;
    const evenShare = 1 / distinctSlots;
    // maxShare ranges from evenShare (perfect) to 1 (all one slot).
    fairSum += 1 - (maxShare - evenShare) / (1 - evenShare);
  }
  const slotFairness = teams.length ? fairSum / teams.length : 1;
  // Field fairness, same idea across the fields a division uses.
  let fieldSum = 0;
  const distinctFields = new Set(games.map((g) => String(g.field ?? "").trim().toLowerCase())).size || 1;
  for (const id of teams) {
    const counts = Object.values(byField[id] ?? {});
    const n = total[id] ?? 0;
    if (n === 0 || distinctFields === 1) { fieldSum += 1; continue; }
    const maxShare = Math.max(...counts) / n;
    const evenShare = 1 / distinctFields;
    fieldSum += 1 - (maxShare - evenShare) / (1 - evenShare);
  }
  const fieldFairness = teams.length ? fieldSum / teams.length : 1;
  // Weekend balance: only meaningful when the schedule uses both kinds of day.
  const usesBoth = Object.keys(wk).length > 0 && Object.keys(wd).length > 0;
  let wbSum = 0;
  for (const id of teams) {
    const n = total[id] ?? 0;
    wbSum += n === 0 || !usesBoth ? 1 : 1 - Math.abs((wk[id] ?? 0) - (wd[id] ?? 0)) / n;
  }
  const weekendBalance = teams.length ? wbSum / teams.length : 1;
  // Blend: home/away 50, slot fairness 20, venue balance 10, weekend 8, completeness 12.
  const balanceScore = Math.max(0, 1 - spread / 4) * 50;
  const fairnessScore = slotFairness * 20;
  const venueScore = fieldFairness * 10;
  const weekendScore = weekendBalance * 8;
  const completeScore = unscheduled === 0 ? 12 : Math.max(0, 12 - unscheduled * 3);
  const score = Math.round(balanceScore + fairnessScore + venueScore + weekendScore + completeScore);
  const grade =
    score >= 90 ? "A" : score >= 80 ? "B" : score >= 70 ? "C" : score >= 60 ? "D" : "F";
  return { score, homeAwaySpread: spread, slotFairness, unscheduled, fieldFairness, weekendBalance, grade };
}

const BYE = "__bye__";

/** Circle method. Returns n-1 rounds; each round pairs every team once.
 *  With an odd count a BYE placeholder sits out one team per round. */
export function roundRobinRounds(teamIds: string[]): [string, string][][] {
  const ids = [...teamIds];
  if (ids.length < 2) return [];
  if (ids.length % 2 === 1) ids.push(BYE);

  const n = ids.length;
  const fixed = ids[0]!;
  let rotating = ids.slice(1);
  const rounds: [string, string][][] = [];

  for (let r = 0; r < n - 1; r++) {
    const round: [string, string][] = [];
    round.push([fixed, rotating[0]!]);
    for (let i = 1; i < rotating.length - i; i++) {
      round.push([rotating[i]!, rotating[rotating.length - i]!]);
    }
    rounds.push(round.filter(([a, b]) => a !== BYE && b !== BYE));
    rotating = [rotating[rotating.length - 1]!, ...rotating.slice(0, -1)];
  }
  return rounds;
}

/** Add days to a YYYY-MM-DD date without touching the local timezone.
 *  Parsed as UTC noon so a DST boundary can never roll the date backwards. */
/** Sunset as minutes after local midnight (Almanac for Computers method,
 *  good to a couple of minutes). null when the sun never sets or rises. */
export function sunsetMinutes(isoDate: string, lat: number, lng: number, tzOffsetMinutes: number): number | null {
  const [y, m, d] = isoDate.split("-").map(Number);
  if (!y || !m || !d) return null;
  const N = Math.floor((Date.UTC(y, m - 1, d) - Date.UTC(y, 0, 1)) / 86400000) + 1;
  const R = Math.PI / 180;
  const sinD = (x: number) => Math.sin(x * R), cosD = (x: number) => Math.cos(x * R);
  const norm = (x: number) => ((x % 360) + 360) % 360;
  const lngHour = lng / 15;
  const t = N + (18 - lngHour) / 24;
  const M = 0.9856 * t - 3.289;
  const L = norm(M + 1.916 * sinD(M) + 0.02 * sinD(2 * M) + 282.634);
  let RA = norm(Math.atan(0.91764 * Math.tan(L * R)) / R);
  RA = (RA + (Math.floor(L / 90) * 90 - Math.floor(RA / 90) * 90)) / 15;
  const sinDec = 0.39782 * sinD(L);
  const cosDec = Math.cos(Math.asin(sinDec));
  const cosH = (cosD(90.833) - sinDec * sinD(lat)) / (cosDec * cosD(lat));
  if (cosH < -1 || cosH > 1) return null;
  const H = Math.acos(cosH) / R / 15;
  const T = H + RA - 0.06571 * t - 6.622;
  const UT = (((T - lngHour) % 24) + 24) % 24;
  return Math.round((((UT * 60 + tzOffsetMinutes) % 1440) + 1440) % 1440);
}

export function addDays(isoDate: string, days: number): string {
  const [y, m, d] = isoDate.split("-").map(Number);
  const t = Date.UTC(y!, (m ?? 1) - 1, d ?? 1, 12, 0, 0) + days * 86400000;
  return new Date(t).toISOString().slice(0, 10);
}

/** 0 = Sunday .. 6 = Saturday, for a YYYY-MM-DD date. */
export function weekdayOf(isoDate: string): number {
  const [y, m, d] = isoDate.split("-").map(Number);
  return new Date(Date.UTC(y!, (m ?? 1) - 1, d ?? 1, 12, 0, 0)).getUTCDay();
}

export const DAY_NAMES = [
  "Sunday",
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
];

/**
 * The season calendar: an array of weeks, each week an array of dates.
 * A week is a 7-day window from startDate. Dates that are not on a chosen
 * weekday, are blacked out, or fall past endDate are excluded — so a fully
 * blacked-out week comes back empty and simply holds no games.
 */
export function buildCalendar(opts: {
  startDate: string;
  endDate?: string;
  weeks?: number;
  daysOfWeek?: number[];
  blackoutDates?: string[];
  extraDates?: string[];
}): string[][] {
  const extra = new Set((opts.extraDates ?? []).filter(Boolean));
  const days =
    opts.daysOfWeek && opts.daysOfWeek.length > 0
      ? [...new Set(opts.daysOfWeek)].sort((a, b) => a - b)
      : [weekdayOf(opts.startDate)];
  const blackout = new Set(opts.blackoutDates ?? []);
  // Hard ceiling so a bad endDate cannot spin forever.
  const maxWeeks = opts.endDate ? 104 : Math.max(1, Math.floor(opts.weeks ?? 1));

  const calendar: string[][] = [];
  for (let w = 0; w < maxWeeks; w++) {
    const weekStart = addDays(opts.startDate, w * 7);
    if (opts.endDate && weekStart > opts.endDate) break;
    const dates: string[] = [];
    for (let d = 0; d < 7; d++) {
      const date = addDays(weekStart, d);
      if (opts.endDate && date > opts.endDate) continue;
      if (date < opts.startDate) continue;
      if (extra.has(date)) { dates.push(date); continue; }
      if (!days.includes(weekdayOf(date))) continue;
      if (blackout.has(date)) continue;
      dates.push(date);
    }
    calendar.push(dates);
  }
  // Trailing empty weeks add nothing.
  while (calendar.length > 0 && calendar[calendar.length - 1]!.length === 0) {
    calendar.pop();
  }
  return calendar;
}

function orgOf(t: GeneratorTeam): string {
  return String(t.organization ?? "").trim().toLowerCase();
}

export function generateSchedule(opts: GeneratorOptions): GeneratorResult {
  const warnings: string[] = [];
  const teams = opts.teams.filter((t) => t && t.id);
  const byId = new Map(teams.map((t) => [t.id, t]));
  const nameOf = (id: string) => byId.get(id)?.name ?? id;

  const empty = (msg: string): GeneratorResult => ({
    games: [],
    dates: [],
    skippedSameOrg: [],
    skippedBlocked: [],
    unscheduled: [],
    noLegalField: [],
    slotsBlockedByExisting: 0,
    everyPairPlayed: false,
    warnings: [msg],
  });

  if (teams.length < 2) return empty("Need at least two teams to build a schedule.");

  const validFields = opts.fields
    .map((f) => ({
      name: String(f?.name ?? "").trim(),
      times: (f?.times ?? []).map((t) => String(t).trim()).filter(Boolean),
      timesByDay: f?.timesByDay ?? null,
      latestStart: f?.latestStart ?? null,
      latestStartFrom: f?.latestStartFrom ?? null,
      latestStartUntil: f?.latestStartUntil ?? null,
      zone: f?.zone ? String(f.zone).trim().toLowerCase() : null,
      lat: typeof f?.lat === "number" && isFinite(f.lat) ? f.lat : null,
      lng: typeof f?.lng === "number" && isFinite(f.lng) ? f.lng : null,
      noLights: !!f?.noLights,
      availableFrom: f?.availableFrom ?? null,
      availableUntil: f?.availableUntil ?? null,
      days: f?.days ?? null,
      closedDates: f?.closedDates ?? null,
    }))
    .filter(
      (f) =>
        f.name &&
        (f.times.length > 0 ||
          Object.values(f.timesByDay ?? {}).some((a) => a && a.length > 0)),
    );
  /** Start times for a field on a given date: its weekday-specific list when
   *  one is set, otherwise the everyday list. */
  const fieldTimes = (
    f: {
      times: string[];
      timesByDay?: Record<number, string[]> | null;
      latestStart?: string | null;
      latestStartFrom?: string | null;
      latestStartUntil?: string | null;
      noLights?: boolean | null;
      lat?: number | null;
      lng?: number | null;
    },
    date: string,
  ): string[] => {
    const special = f.timesByDay?.[weekdayOf(date)];
    let list = special && special.length ? special.map((t) => String(t).trim()).filter(Boolean) : f.times;
    const cap = minutesOf(f.latestStart ?? null);
    if (cap !== null) {
      const inWindow =
        (!f.latestStartFrom || date >= f.latestStartFrom) &&
        (!f.latestStartUntil || date <= f.latestStartUntil);
      if (inWindow) list = list.filter((t) => { const m = minutesOf(t); return m === null || m <= cap; });
    }
    const pattern = opts.allowedStartsByDay?.[weekdayOf(date)];
    if (pattern && pattern.length) {
      const ok = new Set(pattern.map((t) => minutesOf(t)).filter((m): m is number => m !== null));
      list = list.filter((t) => { const m = minutesOf(t); return m === null || ok.has(m); });
    }
    if (f.noLights && f.lat != null && f.lng != null) {
      const ss = sunsetMinutes(date, f.lat, f.lng, tzOffsetFor(date));
      if (ss !== null) {
        const last = ss - Math.max(0, opts.gameMinutes ?? 90);
        list = list.filter((t) => { const m = minutesOf(t); return m === null || m <= last; });
      }
    }
    return list;
  };
  const tzOffsetFor = (date: string): number => {
    const o = opts.tzOffsetMinutes;
    if (typeof o === "function") return o(date);
    if (typeof o === "number") return o;
    return -new Date(date + "T12:00:00").getTimezoneOffset();
  };
  if (validFields.length === 0) {
    return empty("Add at least one field with at least one start time.");
  }
  // Is a field usable on this date? Honors its own window, weekdays, and
  // closures, independent of the league-wide calendar.
  const fieldAvailable = (
    f: { availableFrom?: string | null; availableUntil?: string | null; days?: number[] | null; closedDates?: string[] | null },
    date: string,
  ): boolean => {
    if (f.availableFrom && date < f.availableFrom) return false;
    if (f.availableUntil && date > f.availableUntil) return false;
    if (f.days && f.days.length && !f.days.includes(weekdayOf(date))) return false;
    if (f.closedDates && f.closedDates.includes(date)) return false;
    return true;
  };

  // Slot-time span and field ranks, for the early/late preference and the
  // showcase-field-first option.
  const allSlotMins = validFields.flatMap((f) =>
    [...f.times, ...Object.values(f.timesByDay ?? {}).flat()].map((t) => minutesOf(t) ?? 0),
  );
  const slotMin = allSlotMins.length ? Math.min(...allSlotMins) : 0;
  const slotMax = allSlotMins.length ? Math.max(...allSlotMins) : 0;
  const slotSpan = Math.max(1, slotMax - slotMin);
  const slotPref = opts.slotPreference ?? "balanced";
  const normFieldName = (f: string) =>
    String(f ?? "").trim().toLowerCase().replace(/\s+/g, " ");
  const fieldRank = new Map(validFields.map((f, i) => [normFieldName(f.name), i]));
  const preferFieldOrder = opts.prioritizeFieldOrder === true;

  // ---- 1. the calendar ---------------------------------------------------
  const calendar = buildCalendar(opts);
  const usableWeeks = calendar.filter((w) => w.length > 0).length;
  if (usableWeeks === 0) {
    return empty(
      "No playable dates. Check the start and end dates, the days of the week, and the off dates.",
    );
  }

  // ---- 2. every pair, in round-robin order -------------------------------
  // A seed shuffles the pairing order, so the same teams land in different
  // weeks and slots across seeds. The set of pairings is unchanged (everyone
  // still meets everyone), only the layout varies.
  let orderedIds = teams.map((t) => t.id);
  if (opts.seed != null) {
    let s = (opts.seed >>> 0) || 1;
    const rnd = () => {
      s = (s * 1664525 + 1013904223) >>> 0;
      return s / 4294967296;
    };
    for (let i = orderedIds.length - 1; i > 0; i--) {
      const j = Math.floor(rnd() * (i + 1));
      const tmp = orderedIds[i]!;
      orderedIds[i] = orderedIds[j]!;
      orderedIds[j] = tmp;
    }
  }
  const rounds = roundRobinRounds(orderedIds);

  // ---- 3. drop blocked and same-organisation pairings --------------------
  const skippedSameOrg: GeneratorResult["skippedSameOrg"] = [];
  const skippedBlocked: GeneratorResult["skippedBlocked"] = [];
  const blocked = new Set(
    (opts.blockedPairs ?? [])
      .filter((p) => Array.isArray(p) && p[0] && p[1])
      .map(([a, b]) => [a, b].sort().join("|")),
  );
  const playable = rounds.map((round) =>
    round.filter(([a, b]) => {
      if (blocked.has([a, b].sort().join("|"))) {
        skippedBlocked.push({ a: nameOf(a), b: nameOf(b) });
        return false;
      }
      const oa = orgOf(byId.get(a)!);
      const ob = orgOf(byId.get(b)!);
      if (oa && ob && oa === ob) {
        skippedSameOrg.push({
          a: nameOf(a),
          b: nameOf(b),
          organization: byId.get(a)?.organization ?? "",
        });
        return false;
      }
      return true;
    }),
  );

  // ---- 4. drop the pairings into the calendar ----------------------------
  const gamesPerWeek = Math.max(1, Math.floor(opts.gamesPerWeek ?? 1));
  const sameOpponent = (opts.weeklyPairing ?? "same-opponent") === "same-opponent";
  const roundsPerWeek = sameOpponent ? 1 : gamesPerWeek;
  const gamesPerMatchup = sameOpponent ? gamesPerWeek : 1;

  const games: GeneratedGame[] = [];
  const unscheduled: GeneratorResult["unscheduled"] = [];
  const noLegalField: GeneratorResult["noLegalField"] = [];
  const noLegalFieldSeen = new Set<string>();
  const playedPairs = new Set<string>();
  const pairKey = (a: string, b: string) => [a, b].sort().join("|");
  const usedDates: string[] = [];
  let slotsBlockedByExisting = 0;

  // ---- what the rest of the league has already taken ---------------------
  // Existing games make two things unavailable: the field slot itself, and the
  // teams playing in it. Both are indexed up front so the placement loop below
  // stays a cheap lookup rather than a scan per candidate slot.
  const gameMinutes = Math.max(0, Math.floor(opts.gameMinutes ?? 0));
  const normField = (f: string | null | undefined) =>
    String(f ?? "").trim().toLowerCase().replace(/\s+/g, " ");

  // Linked teams (one coach, two rosters) share one busy identity, so a
  // booking for either blocks both. Ids arriving through existingGames from
  // other divisions resolve through the same map, which is what makes the
  // coach conflict hold across the whole league, not just one run.
  const busyIdOf = new Map<string, string>();
  (opts.linkedTeamIds ?? []).forEach((group, gi) => {
    for (const id of group ?? []) if (id) busyIdOf.set(id, `__linked_${gi}`);
  });
  const busyKey = (id: string) => busyIdOf.get(id) ?? id;

  // date -> every start time in play across all fields, for the league-wide
  // simultaneous-games cap (umpire capacity).
  const startsOnDate = new Map<string, number[]>();
  const maxSim =
    opts.maxSimultaneousGames != null && opts.maxSimultaneousGames > 0
      ? Math.floor(opts.maxSimultaneousGames)
      : null;
  const noteStart = (date: string, mins: number) => {
    startsOnDate.set(date, [...(startsOnDate.get(date) ?? []), mins]);
  };
  // date|field -> start times in minutes that are occupied
  const busyField = new Map<string, number[]>();
  // date|busyKey(team) -> start times that identity is committed to
  const busyTeam = new Map<string, number[]>();
  // date|teamId -> starts for THIS team alone. Day caps and gap rules are
  // per team, while the overlap blocking above is per linked identity.
  const teamStarts = new Map<string, number[]>();
  // teamId -> dates it plays, for the days-of-rest rule.
  const teamDates = new Map<string, Set<string>>();
  // date|teamId -> the field of each start, for the travel-between-fields rule.
  const teamFields = new Map<string, string[]>();
  const noteTeamBooking = (tid: string, date: string, mins: number, field?: string) => {
    const bk = `${date}|${busyKey(tid)}`;
    busyTeam.set(bk, [...(busyTeam.get(bk) ?? []), mins]);
    const tk = `${date}|${tid}`;
    teamStarts.set(tk, [...(teamStarts.get(tk) ?? []), mins]);
    teamFields.set(tk, [...(teamFields.get(tk) ?? []), normField(field ?? "")]);
    let ds = teamDates.get(tid);
    if (!ds) teamDates.set(tid, (ds = new Set()));
    ds.add(date);
  };
  // Length of every booked game, by date|field|start and date|team|start, so
  // a 105 minute game and a 60 minute game are each checked at their own size.
  const bookedLen = new Map<string, number>();
  const lenAt = (key: string, start: number) => bookedLen.get(`${key}|${start}`) ?? gameMinutes;
  for (const eg of opts.existingGames ?? []) {
    const mins = minutesOf(eg.time);
    if (mins === null) continue; // no time to compare against
    const len = eg.minutes != null && eg.minutes > 0 ? Math.floor(eg.minutes) : gameMinutes;
    const f = normField(eg.field);
    if (f) {
      const key = `${eg.date}|${f}`;
      const list = busyField.get(key);
      if (list) list.push(mins);
      else busyField.set(key, [mins]);
      bookedLen.set(`${key}|${mins}`, len);
    }
    noteStart(eg.date, mins);
    for (const tid of [eg.away_team_id, eg.home_team_id]) {
      if (!tid) continue;
      noteTeamBooking(tid, eg.date, mins, eg.field ?? "");
      bookedLen.set(`${eg.date}|${busyKey(tid)}|${mins}`, len);
      bookedLen.set(`${eg.date}|${tid}|${mins}`, len);
    }
  }

  /** Does a candidate start time collide with anything already booked? Same
   *  overlap rule the conflict checker uses, so the generator can never emit a
   *  schedule that findConflicts would then reject. */
  const collides = (taken: number[] | undefined, start: number, key = "") => {
    if (!taken) return false;
    if (gameMinutes <= 0) return taken.includes(start);
    return taken.some((t) => start < t + lenAt(key, t) && t < start + gameMinutes);
  };

  const fieldBuffer = Math.max(0, Math.floor(opts.fieldBufferMinutes ?? 0));
  const collidesOnField = (taken: number[] | undefined, start: number, key = "") => {
    if (!taken) return false;
    if (gameMinutes <= 0) return taken.includes(start);
    const span = gameMinutes + fieldBuffer;
    return taken.some((t) => start < t + lenAt(key, t) + fieldBuffer && t < start + span);
  };
  const slotTaken = (date: string, field: string, time: string) => {
    const mins = minutesOf(time);
    if (mins === null) return false;
    const key = `${date}|${normField(field)}`;
    return collidesOnField(busyField.get(key), mins, key);
  };

  const teamBusy = (teamId: string, date: string, time: string) => {
    const mins = minutesOf(time);
    if (mins === null) return false;
    const key = `${date}|${busyKey(teamId)}`;
    return collides(busyTeam.get(key), mins, key);
  };

  /** Record a placement so later matchups in this same run see it too. */
  const markTaken = (date: string, field: string, time: string, a: string, b: string) => {
    const mins = minutesOf(time);
    if (mins === null) return;
    const fk = `${date}|${normField(field)}`;
    busyField.set(fk, [...(busyField.get(fk) ?? []), mins]);
    noteStart(date, mins);
    for (const tid of [a, b]) noteTeamBooking(tid, date, mins, field);
  };
  /** Would one more game at this start push the league past its umpire cap? */
  const overCapacity = (date: string, time: string) => {
    if (maxSim === null) return false;
    const mins = minutesOf(time);
    if (mins === null) return false;
    const starts = startsOnDate.get(date) ?? [];
    const overlapping = starts.filter((t) =>
      gameMinutes <= 0 ? t === mins : mins < t + gameMinutes && t < mins + gameMinutes,
    ).length;
    return overlapping >= maxSim;
  };

  // Fields a given matchup is allowed to use at all, cached per pair.
  const asConflictTeam = (id: string): ConflictTeam | undefined => {
    const t = byId.get(id);
    return t ? { id: t.id, name: t.name, allowedFields: t.allowedFields } : undefined;
  };
  const legalFieldCache = new Map<string, Set<string> | null>();
  const legalFieldsSet = (a: string, b: string): Set<string> | null => {
    const key = pairKey(a, b);
    if (legalFieldCache.has(key)) return legalFieldCache.get(key)!;
    const allowed = legalFieldsFor(
      asConflictTeam(a),
      asConflictTeam(b),
      validFields.map((f) => f.name),
    );
    // null means "no restriction", which is not the same as "no legal field".
    const unrestricted =
      (byId.get(a)?.allowedFields ?? []).length === 0 &&
      (byId.get(b)?.allowedFields ?? []).length === 0;
    let set: Set<string> | null = unrestricted ? null : new Set(allowed.map(normField));
    if (opts.homeFieldRule === "require") {
      const homes = [a, b]
        .map((t) => String(byId.get(t)?.homeField ?? "").trim())
        .filter(Boolean)
        .map(normField);
      if (homes.length) {
        const hs = new Set(homes);
        set = set ? new Set([...set].filter((f) => hs.has(f))) : hs;
      }
    }
    legalFieldCache.set(key, set);
    return set;
  };

  // Running fairness counters. These are what stop one team being home seven
  // times out of ten, or always drawing the 9am slot.
  const homeCount = new Map<string, number>();
  const timeCount = new Map<string, Map<string, number>>(); // team -> time -> n
  const bump = (m: Map<string, number>, k: string) => m.set(k, (m.get(k) ?? 0) + 1);
  const timesFor = (id: string) => {
    let m = timeCount.get(id);
    if (!m) timeCount.set(id, (m = new Map()));
    return m;
  };
  const unavailableOn = (id: string, date: string) => {
    const t = byId.get(id);
    if ((t?.unavailable ?? []).includes(date)) return true;
    const days = t?.allowedDays;
    if (days && days.length && !days.includes(weekdayOf(date))) return true;
    return false;
  };
  const homeFieldOf = (id: string) => String(byId.get(id)?.homeField ?? "").trim();

  // ---- season-shape rules ---------------------------------------------------
  const target =
    opts.targetGamesPerTeam != null && opts.targetGamesPerTeam > 0
      ? Math.floor(opts.targetGamesPerTeam)
      : null;
  const targetOf = (id: string): number | null => {
    const own = byId.get(id)?.targetGames;
    return own != null && own > 0 ? Math.floor(own) : target;
  };
  const anyTarget = target !== null || teams.some((t) => (t.targetGames ?? 0) > 0);
  const dhMode = opts.doubleheaders ?? "allow";
  const weekOffset = Math.max(0, Math.floor(opts.weekOffset ?? 0));
  const slotW = opts.slotBalance === "strict" ? 4 : 1;
  const maxIdle = opts.maxIdleDays != null && opts.maxIdleDays > 0 ? Math.floor(opts.maxIdleDays) : null;
  const wkBal = opts.weekendBalance === true;
  const noRematch = Math.max(0, Math.floor(opts.noRematchWeeks ?? 0));
  const maxCH =
    opts.maxConsecutiveHome != null && opts.maxConsecutiveHome > 0 ? Math.floor(opts.maxConsecutiveHome) : null;
  const maxCA =
    opts.maxConsecutiveAway != null && opts.maxConsecutiveAway > 0 ? Math.floor(opts.maxConsecutiveAway) : null;
  const gameCount = new Map<string, number>();
  const wkCount = new Map<string, number>();
  const wdCount = new Map<string, number>();
  const lastMet = new Map<string, number>();
  const streak = new Map<string, { side: "H" | "A"; n: number }>();
  const friWk = opts.fridayIsWeekend === true;
  const isWeekend = (date: string) => { const w = weekdayOf(date); return w === 0 || w === 6 || (friWk && w === 5); };
  const weekendMethod = opts.weekendMethod === true;
  const balanceDays = opts.balanceDays === true;
  const dowCount = new Map<string, Map<number, number>>();
  const dowFor = (id: string) => { let m = dowCount.get(id); if (!m) dowCount.set(id, (m = new Map())); return m; };
  const noteGame = (home: string, away: string, date: string) => {
    bump(gameCount, home);
    bump(gameCount, away);
    for (const t of [home, away]) bump(isWeekend(date) ? wkCount : wdCount, t);
    const sh = streak.get(home);
    streak.set(home, sh && sh.side === "H" ? { side: "H", n: sh.n + 1 } : { side: "H", n: 1 });
    const sa = streak.get(away);
    streak.set(away, sa && sa.side === "A" ? { side: "A", n: sa.n + 1 } : { side: "A", n: 1 });
  };
  const gamesOfTeam = (id: string) => gameCount.get(id) ?? 0;
  const lastHost = new Map<string, string>();
  const skipLeft = new Map<string, number>();
  for (const pg of opts.alreadyPlayed ?? []) {
    if (!pg || !pg.a || !pg.b || !byId.has(pg.a) || !byId.has(pg.b)) continue;
    const pk = [pg.a, pg.b].sort().join("|");
    skipLeft.set(pk, (skipLeft.get(pk) ?? 0) + 1);
    gameCount.set(pg.a, (gameCount.get(pg.a) ?? 0) + 1);
    gameCount.set(pg.b, (gameCount.get(pg.b) ?? 0) + 1);
    if (pg.home) { homeCount.set(pg.home, (homeCount.get(pg.home) ?? 0) + 1); lastHost.set(pk, pg.home); }
    if (pg.week != null) lastMet.set(pk, pg.week);
    if (pg.date) { for (const t of [pg.a, pg.b]) { let ds = teamDates.get(t); if (!ds) teamDates.set(t, (ds = new Set())); ds.add(pg.date); } }
  }
  // Travel zones and venue balance.
  const zoneOfField = new Map(validFields.map((f) => [normField(f.name), f.zone]));
  const teamZone = (id: string) => {
    const z = byId.get(id)?.zone;
    return z ? String(z).trim().toLowerCase() : null;
  };
  const zonesInUse = validFields.some((f) => f.zone) && teams.some((t) => t.zone);
  const travelPenalty = opts.travelPenalty != null ? Math.max(0, opts.travelPenalty) : 6;
  const maxOutZone =
    opts.maxOutOfZonePerWeek != null && opts.maxOutOfZonePerWeek >= 0 ? Math.floor(opts.maxOutOfZonePerWeek) : null;
  const outOfZone = (id: string, field: string) => {
    const tz = teamZone(id), fz = zoneOfField.get(normField(field));
    return !!(tz && fz && tz !== fz);
  };
  // Mile based travel.
  const coordOf = new Map<string, { lat: number; lng: number }>();
  for (const f of validFields) if (f.lat !== null && f.lng !== null) coordOf.set(normField(f.name), { lat: f.lat, lng: f.lng });
  const fieldMiles = (fa: string, fb: string): number | null => {
    const a = coordOf.get(normField(fa)), b = coordOf.get(normField(fb));
    if (!a || !b) return null;
    if (normField(fa) === normField(fb)) return 0;
    return milesBetween(a.lat, a.lng, b.lat, b.lng);
  };
  const milesFromHome = (id: string, field: string): number | null => {
    const hf = homeFieldOf(id);
    return hf ? fieldMiles(hf, field) : null;
  };
  const leagueRadius = opts.maxMilesFromHome != null && opts.maxMilesFromHome > 0 ? opts.maxMilesFromHome : null;
  const radiusOf = (id: string): number | null => {
    const own = byId.get(id)?.maxMilesFromHome;
    return own != null && own > 0 ? own : leagueRadius;
  };
  const maxLast = opts.maxMilesFromLast != null && opts.maxMilesFromLast > 0 ? opts.maxMilesFromLast : null;
  const preferCloser = opts.preferCloser === true;
  const milesUsed = coordOf.size > 0 && (leagueRadius !== null || maxLast !== null || preferCloser || teams.some((t) => (t.maxMilesFromHome ?? 0) > 0));
  // Drive minutes from a routing service, keyed by field name.
  const drive = new Map<string, Map<string, number>>();
  for (const [fa, row] of Object.entries(opts.driveMinutes ?? {})) {
    const inner = new Map<string, number>();
    for (const [fb, v] of Object.entries(row ?? {})) if (typeof v === "number" && isFinite(v)) inner.set(normField(fb), v);
    drive.set(normField(fa), inner);
  }
  const driveMin = (fa: string, fb: string): number | null => {
    if (normField(fa) === normField(fb)) return 0;
    const v = drive.get(normField(fa))?.get(normField(fb));
    return v == null ? null : v;
  };
  const leagueMinutes = opts.maxMinutesFromHome != null && opts.maxMinutesFromHome > 0 ? opts.maxMinutesFromHome : null;
  const minutesCapOf = (id: string): number | null => {
    const own = byId.get(id)?.maxMinutesFromHome;
    return own != null && own > 0 ? own : leagueMinutes;
  };
  const driveUsed = drive.size > 0 && (leagueMinutes !== null || teams.some((t) => (t.maxMinutesFromHome ?? 0) > 0));
  const driveBlocks = (id: string, field: string) => {
    const cap = minutesCapOf(id);
    if (cap === null) return false;
    const hf = homeFieldOf(id);
    if (!hf) return false;
    const d = driveMin(hf, field);
    return d !== null && d > cap;
  };
  const radiusBlocks = (id: string, field: string) => {
    const cap = radiusOf(id);
    if (cap === null) return false;
    const d = milesFromHome(id, field);
    return d !== null && d > cap;
  };
  const lastGameBlocks = (id: string, date: string, field: string) => {
    if (maxLast === null) return false;
    for (const prior of teamFields.get(`${date}|${id}`) ?? []) {
      if (!prior) continue;
      const d = fieldMiles(prior, field);
      if (d !== null && d > maxLast) return true;
    }
    return false;
  };
  const fieldCount = new Map<string, Map<string, number>>();
  const fieldsFor = (id: string) => {
    let m = fieldCount.get(id);
    if (!m) fieldCount.set(id, (m = new Map()));
    return m;
  };
  const oddDH = opts.oddTeams === "doubleheader" && teams.length % 2 === 1;
  const extraCount = new Map<string, number>();

  // ---- day-level fairness rules ------------------------------------------
  const dayNum = (iso: string) => {
    const [y, m, d] = iso.split("-").map(Number);
    return Math.floor(Date.UTC(y!, (m ?? 1) - 1, d ?? 1, 12) / 86400000);
  };
  const minDaysRest = Math.max(0, Math.floor(opts.minDaysRest ?? 0));
  const maxPerDay =
    opts.maxPerTeamPerDay != null && opts.maxPerTeamPerDay > 0
      ? Math.floor(opts.maxPerTeamPerDay)
      : null;
  const minGap = Math.max(0, Math.floor(opts.minGapMinutes ?? 0));
  const maxGap =
    opts.maxGapMinutes != null && opts.maxGapMinutes > 0
      ? Math.floor(opts.maxGapMinutes)
      : null;
  const timeWindowBlocks = (id: string, mins: number) => {
    const t = byId.get(id);
    const lo = minutesOf(t?.earliestTime ?? null);
    const hi = minutesOf(t?.latestTime ?? null);
    return (lo !== null && mins < lo) || (hi !== null && mins > hi);
  };
  /** Would `starts` new games on `date` break this team's day rules? Checks
   *  against what the team already has booked, league-wide. A doubleheader
   *  block is deliberately not gap-checked against itself: back to back is
   *  the whole point of one. */
  const travelMin = Math.max(0, Math.floor(opts.travelMinutesBetweenFields ?? 0));
  const dayRulesBlock = (id: string, date: string, starts: number[], field?: string): boolean => {
    const existing = teamStarts.get(`${date}|${id}`) ?? [];
    const existingFields = teamFields.get(`${date}|${id}`) ?? [];
    if (maxPerDay !== null && existing.length + starts.length > maxPerDay) return true;
    if (minDaysRest > 1) {
      const dn = dayNum(date);
      for (const d of teamDates.get(id) ?? []) {
        if (d === date) continue;
        if (Math.abs(dayNum(d) - dn) < minDaysRest) return true;
      }
    }
    if (existing.length && (minGap > 0 || maxGap !== null || travelMin > 0 || drive.size > 0)) {
      for (const s of starts) {
        let nearest = Infinity;
        for (let i = 0; i < existing.length; i++) {
          const t = existing[i]!;
          // end-of-one to start-of-the-other distance
          const dist = s >= t ? s - (t + lenAt(`${date}|${id}`, t)) : t - (s + gameMinutes);
          nearest = Math.min(nearest, dist);
          const otherField = existingFields[i] ?? "";
          const differentField = (travelMin > 0 || drive.size > 0) && field != null && otherField && normField(field) !== otherField;
          const pairMin = differentField ? (driveMin(field!, otherField) ?? travelMin) : 0;
          const need = differentField ? Math.max(minGap, pairMin) : minGap;
          if (need > 0 && dist < need) return true;
        }
        if (maxGap !== null && nearest > maxGap) return true;
      }
    }
    return false;
  };
  const homeOnlyBlocks = (id: string, date: string, field: string) => {
    const days = byId.get(id)?.homeOnlyDays;
    if (!days || !days.length || !days.includes(weekdayOf(date))) return false;
    const hf = homeFieldOf(id);
    return !!hf && normField(hf) !== normField(field);
  };

  // ---- 4a. pin the required matchups first -------------------------------
  // Placed before the round robin so everything else works around them. Each
  // is dropped from `playable` on success so it is never scheduled twice.
  const weekOfDate = new Map<string, number>();
  calendar.forEach((wk, i) => wk.forEach((d) => weekOfDate.set(d, i + 1)));
  const requiredSet = new Set<string>();
  for (const req of opts.requiredMatchups ?? []) {
    if (!req || !req.a || !req.b || req.a === req.b) continue;
    const a = req.a;
    const b = req.b;
    if (!byId.has(a) || !byId.has(b)) continue; // not in this division
    const pk = pairKey(a, b);
    if (blocked.has(pk) || requiredSet.has(pk)) continue;

    let candidates: string[];
    if (req.date && weekOfDate.has(req.date)) {
      candidates = [req.date];
    } else if (req.date) {
      const target = dayNum(req.date);
      candidates = [...weekOfDate.keys()].sort(
        (x, y) => Math.abs(dayNum(x) - target) - Math.abs(dayNum(y) - target),
      );
    } else if (req.week != null && calendar[req.week - 1]?.length) {
      candidates = calendar[req.week - 1]!.slice();
    } else {
      candidates = [...weekOfDate.keys()].sort();
    }

    const legal = legalFieldsSet(a, b);
    // Try either team's home field first, so a pinned game still lands where
    // the team hosts when it can.
    const orderedFields = [...validFields].sort((f1, f2) => {
      const h1 = homeFieldOf(a) === f1.name || homeFieldOf(b) === f1.name ? 0 : 1;
      const h2 = homeFieldOf(a) === f2.name || homeFieldOf(b) === f2.name ? 0 : 1;
      return h1 - h2;
    });
    let placed = false;
    for (const date of candidates) {
      if (unavailableOn(a, date) || unavailableOn(b, date)) continue;
      for (const f of orderedFields) {
        if (req.field && normField(f.name) !== normField(req.field)) continue;
        if (legal && !legal.has(normField(f.name))) continue;
        if (!fieldAvailable(f, date)) continue; // field off on this date
        for (const time of fieldTimes(f, date)) {
          const mins = minutesOf(time);
          if (mins === null) continue;
          if (req.time && mins !== minutesOf(req.time)) continue;
          if (timeWindowBlocks(a, mins) || timeWindowBlocks(b, mins)) continue;
          if (slotTaken(date, f.name, time)) continue;
          if (overCapacity(date, time)) continue;
          if (teamBusy(a, date, time) || teamBusy(b, date, time)) continue;
          if (dayRulesBlock(a, date, [mins], f.name) || dayRulesBlock(b, date, [mins], f.name)) continue;
          if (homeOnlyBlocks(a, date, f.name) || homeOnlyBlocks(b, date, f.name)) continue;
          if ((milesUsed || driveUsed) && (radiusBlocks(a, f.name) || radiusBlocks(b, f.name) || driveBlocks(a, f.name) || driveBlocks(b, f.name) || lastGameBlocks(a, date, f.name) || lastGameBlocks(b, date, f.name))) continue;
          const aHome = homeFieldOf(a) === f.name;
          const bHome = homeFieldOf(b) === f.name;
          const home = aHome && !bHome ? a : bHome && !aHome ? b : b;
          const away = home === a ? b : a;
          bump(homeCount, home);
          bump(timesFor(a), time);
          bump(timesFor(b), time);
          markTaken(date, f.name, time, a, b);
          games.push({
            date,
            time,
            field: f.name,
            away_team_id: away,
            home_team_id: home,
            ...(opts.division ? { division: opts.division } : {}),
            week: (weekOfDate.get(date) ?? 0) + weekOffset,
            status: "scheduled",
            required: true,
            ...(req.label ? { label: req.label } : {}),
          });
          noteGame(home, away, date);
          lastMet.set(pk, weekOfDate.get(date) ?? 0);
          playedPairs.add(pk);
          requiredSet.add(pk);
          placed = true;
          break;
        }
        if (placed) break;
      }
      if (placed) break;
    }
    if (!placed) {
      warnings.push(
        `Could not pin ${nameOf(a)} vs ${nameOf(b)}${req.label ? ` (${req.label})` : ""} to its target, so it was scheduled normally. Free a slot on that date to place it there.`,
      );
    }
  }
  // Drop successfully pinned pairs from the round robin so they are not
  // scheduled a second time.
  if (requiredSet.size) {
    for (let r = 0; r < playable.length; r++) {
      playable[r] = playable[r]!.filter(([a, b]) => !requiredSet.has(pairKey(a, b)));
    }
  }

  const pools = opts.pools && Object.keys(opts.pools).length ? opts.pools : null;
  const poolCycles = Math.max(0, Math.floor(opts.poolCycles ?? 2));
  const crossCycles = Math.max(0, Math.floor(opts.crossPoolCycles ?? 1));
  const maxCycles =
    opts.maxCycles != null && opts.maxCycles > 0
      ? Math.floor(opts.maxCycles)
      : pools
        ? Math.max(1, poolCycles, crossCycles)
        : null;
  // A mid season rebuild continues the round robin where the frozen weeks left
  // off, so the cursor starts past the rounds those weeks already covered.
  let roundCursor = 0;
  let weekNo = (0) + weekOffset;
  // Matchups pushed to a later week by a rule (a rematch too soon, a team at
  // its weekly cap). Each carries a try count so it cannot ride forever.
  let carry: { a: string; b: string; cycle: number; tries: number }[] = [];

  for (const weekDates of calendar) {
    if (weekDates.length === 0) continue; // an off week
    // Every team has its target games: the season is complete.
    if (anyTarget && teams.every((t) => { const c = targetOf(t.id); return c !== null && gamesOfTeam(t.id) >= c; })) break;
    // Every pair has met maxCycles times: the season is over, stop cleanly
    // instead of stretching matchups across the remaining calendar.
    if (maxCycles !== null && roundCursor >= playable.length * maxCycles) break;
    weekNo += 1;
    weekDates.forEach((d) => usedDates.push(d));

    // Slots for this week, grouped into "runs" — one run per date+field, its
    // times in order. A run is the unit a same-opponent block has to fit
    // inside, since a doubleheader is played on one field back to back.
    const runs: { date: string; field: string; time: string }[][] = [];
    for (const date of weekDates) {
      for (const f of validFields) {
        if (!fieldAvailable(f, date)) continue; // this field is off today
        const todays = fieldTimes(f, date);
        if (!todays.length) continue;
        runs.push(todays.map((time) => ({ date, field: f.name, time })));
      }
    }
    // Which slots are still free, per run, and how many games each run has
    // taken — used to spread across days and fields rather than filling one
    // first. Tracked slot by slot rather than as a "next free index": a single
    // game must be able to take the LATE slot while the early one is still
    // open, otherwise a team can never be moved off the 9am it always draws.
    const free = runs.map((r) => r.map(() => true));
    const load = runs.map(() => 0);
    const outZoneWeek = new Map<string, number>();
    const weekWk = new Map<string, number>();
    const weekWd = new Map<string, number>();

    /**
     * Choose the best free slots for one matchup, rather than taking the next
     * in line. Lower score wins. This is where fairness lives:
     *
     *   - a team never plays on a date it said it is unavailable (hard block)
     *   - the slot time each team has had least is preferred, so nobody owns
     *     the 9am game all season
     *   - a team's home field pulls its games towards that field
     *   - lightly-loaded runs are preferred, which keeps the spread across
     *     days and fields that the round-robin cursor used to give
     */
    const takeSlots = (n: number, a: string, b: string) => {
      const legal = legalFieldsSet(a, b);
      let best: { r: number; i: number; score: number } | null = null;
      for (let r = 0; r < runs.length; r++) {
        // Every start position whose next n slots are all still free. For a
        // single game that is any free slot; for a block it must be n in a row
        // on the one field, which is what a doubleheader is.
        for (let i = 0; i + n <= runs[r]!.length; i++) {
          let ok = true;
          for (let k = 0; k < n; k++) if (!free[r]![i + k]) { ok = false; break; }
          if (!ok) continue;
          const window = runs[r]!.slice(i, i + n);
          // Hard block: either team unavailable on that date.
          if (
            window.some((s) => unavailableOn(a, s.date) || unavailableOn(b, s.date))
          ) {
            continue;
          }
          // Hard block: a start time outside a team's earliest/latest window.
          if (
            window.some((s) => {
              const m = minutesOf(s.time);
              return m !== null && (timeWindowBlocks(a, m) || timeWindowBlocks(b, m));
            })
          ) {
            continue;
          }
          // Hard block: day caps, days-of-rest, and same-day gap rules.
          {
            const winByDate = new Map<string, number[]>();
            for (const s of window) {
              const m = minutesOf(s.time);
              if (m === null) continue;
              winByDate.set(s.date, [...(winByDate.get(s.date) ?? []), m]);
            }
            let dayBlocked = false;
            for (const [d, starts] of winByDate) {
              if (dayRulesBlock(a, d, starts, window[0]!.field) || dayRulesBlock(b, d, starts, window[0]!.field)) {
                dayBlocked = true;
                break;
              }
            }
            if (dayBlocked) continue;
          }
          // Hard block: a "must be at home on this day" team not at its park.
          if (window.some((s) => homeOnlyBlocks(a, s.date, s.field) || homeOnlyBlocks(b, s.date, s.field))) continue;
          // Hard block: outside a team's mile radius, or too far from an
          // earlier game the same day.
          if ((milesUsed || driveUsed) && window.some((s) =>
            radiusBlocks(a, s.field) || radiusBlocks(b, s.field) || driveBlocks(a, s.field) || driveBlocks(b, s.field) ||
            lastGameBlocks(a, s.date, s.field) || lastGameBlocks(b, s.date, s.field))) continue;
          // Hard block: this field is not one both teams may use.
          if (legal && window.some((s) => !legal.has(normField(s.field)))) continue;
          // Hard block: the slot, or one of these teams, is already committed
          // elsewhere in the league. This is what stops division-by-division
          // generation from stacking games onto one field.
          if (
            window.some(
              (s) =>
                slotTaken(s.date, s.field, s.time) ||
                teamBusy(a, s.date, s.time) ||
                teamBusy(b, s.date, s.time),
            )
          ) {
            slotsBlockedByExisting += 1;
            continue;
          }
          // Hard block: no umpire left for one more game at this time.
          if (window.some((s) => overCapacity(s.date, s.time))) continue;
          // The slots in this window must also work against EACH OTHER. Only
          // games already on the board were being checked, so a doubleheader
          // could be handed two slots that physically overlap.
          {
            let selfClash = false;
            const byDate = new Map<string, { m: number; len: number; field: string }[]>();
            for (const s of window) {
              const m = minutesOf(s.time);
              if (m === null) continue;
              const list = byDate.get(s.date) ?? [];
              list.push({ m, len: gameMinutes, field: normField(s.field) });
              byDate.set(s.date, list);
            }
            for (const [, list] of byDate) {
              list.sort((x, y) => x.m - y.m);
              for (let q = 1; q < list.length && !selfClash; q++) {
                const prev = list[q - 1]!, cur = list[q]!;
                const gap = cur.m - (prev.m + prev.len);
                // Same field: the next game cannot start before this one ends,
                // plus whatever turnaround the league asked for.
                if (prev.field === cur.field && gap < fieldBuffer) selfClash = true;
                // Either field: the two teams are in both games, so the rest
                // between them is a real constraint.
                if (gap < 0) selfClash = true;
                if (minGap > 0 && gap < minGap) selfClash = true;
                if (maxGap !== null && gap > maxGap) selfClash = true;
              }
              if (selfClash) break;
            }
            if (selfClash) continue;
          }
          let score = load[r]! * 2; // spread across days and fields
          for (const s of window) {
            score += ((timesFor(a).get(s.time) ?? 0) + (timesFor(b).get(s.time) ?? 0)) * slotW;
            if (homeFieldOf(a) === s.field || homeFieldOf(b) === s.field) score -= 3;
            const m = minutesOf(s.time);
            if (m !== null && slotPref === "early") score += ((m - slotMin) / slotSpan) * 4;
            else if (m !== null && slotPref === "late") score += ((slotMax - m) / slotSpan) * 4;
            if (preferFieldOrder) score += (fieldRank.get(normField(s.field)) ?? 0) * 1.5;
            // Travel: steer away from out-of-zone fields; cap them per week.
            if (zonesInUse) {
              for (const t of [a, b]) {
                if (!outOfZone(t, s.field)) continue;
                if (maxOutZone !== null && (outZoneWeek.get(t) ?? 0) >= maxOutZone) { score = Infinity; break; }
                score += travelPenalty;
              }
              if (score === Infinity) break;
            }
            // Venue balance: when neither team has a home field, prefer the
            // field each has used least, so nobody lives at one park.
            if (!homeFieldOf(a) && !homeFieldOf(b)) {
              score += ((fieldsFor(a).get(normField(s.field)) ?? 0) + (fieldsFor(b).get(normField(s.field)) ?? 0)) * 0.5;
            }
            // Doubleheader opinion: is either team already playing that day?
            const already =
              (teamStarts.get(`${s.date}|${a}`)?.length ?? 0) +
              (teamStarts.get(`${s.date}|${b}`)?.length ?? 0);
            if (dhMode === "avoid" && already > 0) score += 25;
            else if (dhMode === "prefer" && already > 0) score -= 6;
            // Closer is better: each mile from a team's home park costs a little.
            if (preferCloser) {
              for (const t of [a, b]) {
                const d = milesFromHome(t, s.field);
                if (d !== null) score += d * 0.15;
              }
            }
            // Weekend method: one weekday game and one weekend game a week.
            if (weekendMethod) {
              const wk = isWeekend(s.date);
              for (const t of [a, b]) {
                if ((wk ? weekWk : weekWd).get(t) ?? 0) score += 40;
              }
            }
            // Spread across the weekdays a team plays on.
            if (balanceDays) {
              const dow = weekdayOf(s.date);
              score += ((dowFor(a).get(dow) ?? 0) + (dowFor(b).get(dow) ?? 0)) * 0.75;
            }
            // Weekend and weeknight balance: nudge each team toward whichever
            // it has had less of.
            if (wkBal) {
              const wk = isWeekend(s.date);
              for (const t of [a, b]) {
                const w = wkCount.get(t) ?? 0, d = wdCount.get(t) ?? 0;
                score += (wk ? Math.max(0, w - d) : Math.max(0, d - w)) * 2;
              }
            }
          }
          if (score === Infinity) continue;
          if (best === null || score < best.score) best = { r, i, score };
        }
      }
      if (best === null) return null;
      const { r, i } = best;
      for (let k = 0; k < n; k++) free[r]![i + k] = false;
      load[r] = load[r]! + 1;
      const picked = runs[r]!.slice(i, i + n);
      // Feed the placement back into the busy index so the next matchup in this
      // same run sees it, exactly as it would see a pre-existing game.
      picked.forEach((s) => markTaken(s.date, s.field, s.time, a, b));
      return picked;
    };

    // This week's matchups: anything carried over first, then this week's rounds.
    const weekMatchups: { a: string; b: string; cycle: number; tries: number }[] = carry;
    carry = [];
    // Pull this week's rounds. A round that was entirely played before a mid
    // season rebuild is consumed without costing a calendar week.
    const pulledIdx: number[] = [];
    let pullGuard = 0;
    while (pulledIdx.length < roundsPerWeek && pullGuard++ < playable.length * 8 + roundsPerWeek) {
      const idx = roundCursor;
      const cycle = Math.floor(idx / playable.length);
      if (maxCycles !== null && cycle >= maxCycles) break;
      roundCursor++;
      let added = 0, skipped = 0;
      (playable[idx % playable.length] ?? []).forEach(([a, b]) => {
        const pk = [a, b].sort().join("|");
        const left = skipLeft.get(pk) ?? 0;
        if (left > 0) { skipLeft.set(pk, left - 1); playedPairs.add(pk); skipped++; return; }
        weekMatchups.push({ a, b, cycle, tries: 0 });
        added++;
      });
      if (added > 0 || skipped === 0) pulledIdx.push(idx);
    }
    if (maxIdle !== null && weekDates.length) {
      const wk0 = dayNum(weekDates[0]!);
      const idleOf = (id: string) => {
        const dates = Array.from(teamDates.get(id) ?? []);
        const last = dates.length ? Math.max(...dates.map(dayNum)) : dayNum(opts.startDate) - 1;
        return wk0 - last;
      };
      weekMatchups.sort((x, y) => {
        const ix = Math.max(idleOf(x.a), idleOf(x.b)) + x.tries * 7;
        const iy = Math.max(idleOf(y.a), idleOf(y.b)) + y.tries * 7;
        return iy - ix;
      });
    }
    const weekCount = new Map<string, number>();
    // Odd team count with doubleheaders on: the round's bye team plays the
    // team that has had the fewest extra games so far.
    if (oddDH) {
      for (const idx of pulledIdx) {
        const cycle = Math.floor(idx / playable.length);
        const round = rounds[idx % rounds.length] ?? [];
        const inRound = new Set(round.flat());
        const bye = orderedIds.find((id) => !inRound.has(id));
        if (!bye) continue;
        const partners = orderedIds.filter((id) => id !== bye && inRound.has(id));
        partners.sort((x, y) => (extraCount.get(x) ?? 0) - (extraCount.get(y) ?? 0) || gamesOfTeam(x) - gamesOfTeam(y));
        const partner = partners.find((pid) => !blocked.has(pairKey(bye, pid)) && !(orgOf(byId.get(bye)!) && orgOf(byId.get(bye)!) === orgOf(byId.get(pid)!)));
        if (partner) { weekMatchups.push({ a: bye, b: partner, cycle, tries: 0 }); extraCount.set(partner, (extraCount.get(partner) ?? 0) + 1); }
      }
    }
    const defer = (m: { a: string; b: string; cycle: number; tries: number }) => {
      if (m.tries >= 8) unscheduled.push({ a: nameOf(m.a), b: nameOf(m.b) });
      else carry.push({ ...m, tries: m.tries + 1 });
    };

    for (const m of weekMatchups) {
      const { a, b } = m;
      // A team at its season target sits this one out.
      if (anyTarget) {
        const ta = targetOf(a), tb = targetOf(b);
        if ((ta !== null && gamesOfTeam(a) >= ta) || (tb !== null && gamesOfTeam(b) >= tb)) continue;
      }
      // Sub-pools: this pair has met as often as its pool relationship allows.
      if (pools) {
        const same = !!pools[a] && pools[a] === pools[b];
        if (m.cycle >= (same ? poolCycles : crossCycles)) continue;
      }
      // Too soon for a rematch: try again in a later week.
      const lm = lastMet.get(pairKey(a, b));
      if (noRematch > 0 && lm !== undefined && weekNo - lm < noRematch) { defer(m); continue; }
      // A team's own weekly cap.
      const capA = byId.get(a)?.maxGamesPerWeek ?? null;
      const capB = byId.get(b)?.maxGamesPerWeek ?? null;
      if (
        (capA != null && capA > 0 && (weekCount.get(a) ?? 0) + gamesPerMatchup > capA) ||
        (capB != null && capB > 0 && (weekCount.get(b) ?? 0) + gamesPerMatchup > capB)
      ) { defer(m); continue; }
      // Neutral-site game where BOTH teams are at the consecutive home cap (or
      // both at the away cap): whoever we pick breaks a rule, so try next week.
      if (!homeFieldOf(a) && !homeFieldOf(b) && (maxCH !== null || maxCA !== null)) {
        const sa = streak.get(a), sb = streak.get(b);
        const bothH = maxCH !== null && sa?.side === "H" && sa.n >= maxCH && sb?.side === "H" && sb.n >= maxCH;
        const bothA = maxCA !== null && sa?.side === "A" && sa.n >= maxCA && sb?.side === "A" && sb.n >= maxCA;
        if (bothH || bothA) { defer(m); continue; }
      }
      // A pairing whose allowed-field sets do not intersect can never be placed,
      // no matter how much calendar is added. Report it as its own problem —
      // telling an admin to "add a field or another start time" when the real
      // fix is a team's eligibility list would send them the wrong way.
      const legal = legalFieldsSet(a, b);
      if (legal && legal.size === 0) {
        const key = pairKey(a, b);
        if (!noLegalFieldSeen.has(key)) {
          noLegalFieldSeen.add(key);
          noLegalField.push({ a: nameOf(a), b: nameOf(b) });
        }
        continue;
      }
      const picked = takeSlots(gamesPerMatchup, a, b);
      if (!picked) {
        unscheduled.push({ a: nameOf(a), b: nameOf(b) });
        continue;
      }
      for (let g = 0; g < gamesPerMatchup; g++) {
        const s = picked[g]!;
        // Who is home. Priority:
        //   1. whoever's home field this is
        //   2. otherwise whoever has been home less so far, which is what
        //      keeps the season from ending 7 home / 3 away
        //   3. within a doubleheader, alternate so neither hosts both
        let home: string;
        let away: string;
        const aHome = homeFieldOf(a) === s.field;
        const bHome = homeFieldOf(b) === s.field;
        const prevHost = opts.pairAlternate ? lastHost.get(pairKey(a, b)) : undefined;
        if (aHome !== bHome) {
          [home, away] = aHome ? [a, b] : [b, a];
        } else if (prevHost && g === 0) {
          // Home and home: the previous visitor hosts this time.
          [home, away] = prevHost === a ? [b, a] : [a, b];
        } else if (g % 2 === 1) {
          // second half of a block: flip whatever the first half did
          const prev = games[games.length - 1]!;
          [home, away] = [prev.away_team_id, prev.home_team_id];
        } else {
          const ha = homeCount.get(a) ?? 0;
          const hb = homeCount.get(b) ?? 0;
          const sA = streak.get(a), sB = streak.get(b);
          if (opts.homeAwayPattern === "alternate" && (sA || sB) && !(sA && sB && sA.side === sB.side)) {
            // Strict alternation: whoever was away last hosts. If only one has
            // history, flip that one; if both were on the same side, fall
            // through to the balance rule.
            const aWantsHome = sA ? sA.side === "A" : sB!.side === "H";
            [home, away] = aWantsHome ? [a, b] : [b, a];
          } else if (ha !== hb) [home, away] = ha < hb ? [a, b] : [b, a];
          else {
            // Tie on season home count: whoever has been away longer hosts.
            const sa0 = streak.get(a), sb0 = streak.get(b);
            const runA = (sa0?.side === "A" ? sa0.n : 0) - (sa0?.side === "H" ? sa0.n : 0);
            const runB = (sb0?.side === "A" ? sb0.n : 0) - (sb0?.side === "H" ? sb0.n : 0);
            [home, away] = runA >= runB ? [a, b] : [b, a];
          }
          // Consecutive home or away caps: flip if the pick would break one
          // and the flip itself is legal.
          const hs = streak.get(home), as = streak.get(away);
          const homeMaxed = maxCH !== null && hs?.side === "H" && hs.n >= maxCH;
          const awayMaxed = maxCA !== null && as?.side === "A" && as.n >= maxCA;
          if (homeMaxed || awayMaxed) {
            const hs2 = streak.get(away), as2 = streak.get(home);
            const flipBreaksHome = maxCH !== null && hs2?.side === "H" && hs2.n >= maxCH;
            const flipBreaksAway = maxCA !== null && as2?.side === "A" && as2.n >= maxCA;
            if (!flipBreaksHome && !flipBreaksAway) [home, away] = [away, home];
          }
        }
        bump(homeCount, home);
        lastHost.set(pairKey(a, b), home);
        bump(timesFor(a), s.time);
        bump(timesFor(b), s.time);
        games.push({
          date: s.date,
          time: s.time,
          field: s.field,
          away_team_id: away,
          home_team_id: home,
          ...(opts.division ? { division: opts.division } : {}),
          week: weekNo,
          status: "scheduled",
        });
        noteGame(home, away, s.date);
        for (const t of [a, b]) {
          bump(fieldsFor(t), normField(s.field));
          if (outOfZone(t, s.field)) bump(outZoneWeek, t);
          bump(isWeekend(s.date) ? weekWk : weekWd, t);
          const dm = dowFor(t), dw = weekdayOf(s.date);
          dm.set(dw, (dm.get(dw) ?? 0) + 1);
        }
      }
      lastMet.set(pairKey(a, b), weekNo);
      bump(weekCount, a);
      bump(weekCount, b);
      if (gamesPerMatchup > 1) { weekCount.set(a, (weekCount.get(a) ?? 0) + gamesPerMatchup - 1); weekCount.set(b, (weekCount.get(b) ?? 0) + gamesPerMatchup - 1); }
      playedPairs.add(pairKey(a, b));
    }
  }
  // Anything still carried at the end never found a legal week.
  for (const m of carry) unscheduled.push({ a: nameOf(m.a), b: nameOf(m.b) });

  // ---- 5. report what the inputs could not fit ---------------------------
  const allowedPairs = new Set<string>();
  playable.forEach((round) =>
    round.forEach(([a, b]) => allowedPairs.add(pairKey(a, b))),
  );
  const everyPairPlayed = [...allowedPairs].every((k) => playedPairs.has(k));

  const weeksForFullRotation = Math.ceil(playable.length / roundsPerWeek);
  if (maxIdle !== null) {
    for (const t of teams) {
      const dates = [...(teamDates.get(t.id) ?? [])].map(dayNum).sort((x, y) => x - y);
      let worst = 0;
      for (let i = 1; i < dates.length; i++) worst = Math.max(worst, dates[i]! - dates[i - 1]!);
      if (worst > maxIdle) warnings.push(`${nameOf(t.id)} goes ${worst} days without a game at one point (limit ${maxIdle}). More start times or fewer blackouts in that stretch would close the gap.`);
    }
  }
  if (anyTarget) {
    const short = teams.filter((t) => { const c = targetOf(t.id); return c !== null && gamesOfTeam(t.id) < c; });
    if (short.length) {
      warnings.push(
        `${short.length} team${short.length === 1 ? "" : "s"} ended below the target of ${target} games ` +
          `(${short.map((t) => `${t.name} ${gamesOfTeam(t.id)}`).join(", ")}). Extend the season, add a game night, or add a field.`,
      );
    }
  }
  if (target === null && usableWeeks < weeksForFullRotation) {
    warnings.push(
      `${usableWeeks} playable week${usableWeeks === 1 ? "" : "s"} is not enough ` +
        `for everyone to play everyone once. That needs ${weeksForFullRotation} ` +
        `at this format. Extend the end date, or add game days.`,
    );
  }
  if (unscheduled.length > 0) {
    warnings.push(
      `${unscheduled.length} matchup${unscheduled.length === 1 ? "" : "s"} had no ` +
        `slot. Add a field, another start time, or another day of the week.`,
    );
  }
  if (skippedSameOrg.length > 0) {
    warnings.push(
      `${skippedSameOrg.length} matchup${skippedSameOrg.length === 1 ? "" : "s"} ` +
        `skipped because both teams are in the same organization.`,
    );
  }
  if (skippedBlocked.length > 0) {
    warnings.push(
      `${skippedBlocked.length} matchup${skippedBlocked.length === 1 ? "" : "s"} ` +
        `skipped because you blocked those teams from playing each other.`,
    );
  }

  if (noLegalField.length > 0) {
    warnings.push(
      `${noLegalField.length} matchup${noLegalField.length === 1 ? "" : "s"} ` +
        `could not be placed because the two teams share no field they are both ` +
        `allowed to use. Widen one of their allowed-field lists.`,
    );
  }
  if (slotsBlockedByExisting > 0) {
    warnings.push(
      `${slotsBlockedByExisting} slot${slotsBlockedByExisting === 1 ? "" : "s"} ` +
        `were already taken by games elsewhere in the league and were worked ` +
        `around, so nothing here double-books an existing game.`,
    );
  }

  return {
    games,
    dates: usedDates,
    skippedSameOrg,
    skippedBlocked,
    unscheduled,
    noLegalField,
    slotsBlockedByExisting,
    everyPairPlayed,
    warnings,
  };
}
